env:
  global:
  - DATE=$(date +%Y-%m-%d)
  - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
  - NATIVESCRIPT_SKIP_POSTINSTALL_TASKS=1
language: node_js
node_js:
- '8'
git:
  submodules: true
install:
- npm install --ignore-scripts
before_script:
- gem install xcodeproj
- gem install cocoapods
- npm install grunt
- node_modules/.bin/grunt enableScripts:false
- grunt rebuild
- "./bin/nativescript error-reporting disable"
- "./bin/nativescript usage-reporting disable"
- npm test
- node_modules/.bin/grunt enableScripts:true
script:
- node_modules/.bin/grunt lint
- node_modules/.bin/grunt pack --no-color
after_success:
- rm -rf s3-publish
- mkdir s3-publish
- cp nativescript*.tgz s3-publish/nativescript.tgz
before_deploy:
- node .travis/add-publishConfig.js $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJL6X6724CSX64X3Q
  secret_access_key:
    secure: a0T/2S+/rkRJqEotWPAr1VELA3k5TGyRw6VmXgBQnkirc6H0Pfu0P2DY8iriO7pnTPDCPAskdBCuk6t+RYw/OCrGDzFPApnAQ7t3tksKPr2bGYqh2HVqbFKZyEbNjzwsgxn7cmLPo936ZTHP2muQItEI3o9Zh9EZ5XHtv0Maw0k=
  bucket: nativescript-ci
  skip_cleanup: true
  local-dir: s3-publish
  upload-dir: build_result
  on:
    branch: master
- provider: npm
  skip_cleanup: true
  email: nativescript@telerik.com
  on:
    branch: master
  api_key:
    secure: "ghoz7UYqvQKZGmAAt2OQ9tIyzzU5o5QKHzvtRpC9ml7WYtW7HxXtC93UCQfylGJKfSJRYCvoJ7IHi6TvOIflNKJD747jYAGtPiaQDG0HGf+GesL/ormhB3MrS7Br6/fkmzlbYHizwwSurM1w8g0hFXERFv9VD3adDWAG63ZGYec="
- provider: npm
  skip_cleanup: true
  email: nativescript@telerik.com
  on:
    branch: release
  api_key:
    secure: "ghoz7UYqvQKZGmAAt2OQ9tIyzzU5o5QKHzvtRpC9ml7WYtW7HxXtC93UCQfylGJKfSJRYCvoJ7IHi6TvOIflNKJD747jYAGtPiaQDG0HGf+GesL/ormhB3MrS7Br6/fkmzlbYHizwwSurM1w8g0hFXERFv9VD3adDWAG63ZGYec="
