env:
  global:
  - DATE=$(date +%Y-%m-%d)
  - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
  - NATIVESCRIPT_SKIP_POSTINSTALL_TASKS=1
language: node_js
node_js:
- '4'
git:
  submodules: true
before_script:
- npm install grunt
- node_modules/.bin/grunt enableScripts:false
- grunt rebuild
- ./bin/nativescript error-reporting disable # force ~/.local dir creation -- some tests rely on it
- ./bin/nativescript usage-reporting disable
- npm test
- node_modules/.bin/grunt enableScripts:true
script:
- node_modules/.bin/grunt lint
- node_modules/.bin/grunt pack --no-color
after_success:
- rm -rf s3-publish
- mkdir s3-publish
- cp nativescript*.tgz s3-publish/nativescript.tgz
before_deploy:
- node .travis/add-publishConfig.js next
deploy:
  - provider: s3
    bucket: nativescript-ci
    access_key_id: AKIAIYSWYOZRFLVKPCTQ
    secret_access_key:
      secure: THGlblH9XdRcTQMc3jm4kpwCB3myl8MGB3v9XjB5ObK4gqxUxuPi6e158LEG9Dgb730MGEYtaAjc9OneH59WAjQOrdcf3GXiGKOiCYzGYZLqVE4pjNDuxHaVGOj7mso4TzMinMCaDSQajTvadCfVmXqgT6p9eSXkiV3V2d2DN6c=
    skip_cleanup: true
    local-dir: s3-publish
    upload-dir: build_result
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: nativescript@telerik.com
    on:
      branch: master
    api_key:
      secure: Ugq6m/y4P5gF15zffYzTKhusn1Csu3ymYLdD+yXgyK3hek9Ms5PKTz4MKgPinlViRCBoQV2fGh0JsCikawIpmQyD+M+FRDKlP2GcXPhFmSN1wVEloxTCwe7H6m7Kl9mo+MJOTS0BN7waCc6yTJBJPxo5nwFgz+DT2srIYndA2h4=
