env:
  global:
    - INTEGRATION_TESTS_NODEJS_VERSION='8.1.0'
    - INTEGRATION_TESTS_NATIVESCRIPT_VERSION='3.4.2'
    - INTEGRATION_TESTS_CORDOVA_VERSION='8.0.0'
    - UNIT_TESTS_NODEJS_VERSION='9'
    - RUN_INTEGRATION_TESTS_FILE_LOCATION='./test/integration/run-tests'
    - secure: IuywIkmD6t8wxh1OpjMgHvvGIzDBDXXahkhlTFsuxN0kowqlWrF9F1gCyMdg7dALJ+rtInISGIm+7UrTbyoNSBPHRkzXyU0p1eDx8shBLYOg8dKxTwUn61zb3ckOMt1sYwOy2x00d6MUIayB0uu5haYUyi4zt8bqs2Mp548oO4r5+Y4/Tnt3lP5/dGFyxOER7HZdb+Ka9KguzhgJeWSF7dRMjQCHCccUO4i2Gp6cQVE8xI2e9nN6SXDwuQrIq8zRcbCh/5sH4R1uEHEKDT5u0gBIN5eBQSkjG7rtBi3Vaif7TsSqRTGUV2njKCIO7Cd8HLHeY9D7WHFMsLXOGo2hGZvdaeq9QXoJ3mswNO0AUP6Smam+Bg8YeHy+x6+/yGIT7N0J0wrZUY3WeEpq3b14+f2YtDhhGS0m3K6uLllOQ+NVHvkgEEVp7y4pxJhTf8e9Gc6ZCoJOAY+NCjI7wnDQ0DbyanoE5JbhyL6oDv1P+sZE9Ixm3fRIZVrUf4g3P31AXL4O4UUdcTjMwUmTktweXGLCKqbtS/XepxtaeUTthacoTYALkjpgDeB3jrOLiEUxVjI2GYH4IRjdutAohVfgEFy8m5KiTdw5pQQFzT+u+T+YRf9N3o5O/BSSJuzpa57nmPa9ShCHNLLahEAVi65fRo1Ols7pU8ZnLxZ7r6PrrwQ=
    - secure: LemZiwC4Yz64wBK6sjgV/4klcTPEg+ChUNkqzAbu0mcLWd/TQYccYc7idVV6+2AdNJfkL9vXCHMAVozWsgDM8EkpnP/ekH3mtNIz3ZmuGCgRWv5D6Bm9pkrtJxElqJ30WYHbMThH8KLQMOib5iyH+BSPNQqgcwhojpS9jF1CpffJTQg+3fRQbuitJMcYmlvkhoYoQyhQSXRwXoQoNRhvC/4UXp5BQq/x5jGA51WadfWy3JmXqdkrts9xZ2xVkvmVPb0/OlG79WzxAqyH2wmmzKrxWNjBiskBrpdIKM3a8j7OlIUwOCms3/6pBTLQQXDB9IAC2kt12XGTE+wXCqicqRaDGUn+3ZIdtEgcI1j5Cx+waY+6Hg1eRxtGaZRZMjjXng2U4RhTkyBmLu1nZQZ8bSLWJmCprtK4Y/efM8U6dwNjhxPVDEx6r569cMrzjtBCr9juAMGL4pmRIQ2OJ63uLUmyPEi6WsYuvumifLwECRHV2XA6dsWtiVgFwiVhO+1IuyfGUDA4uZO5ULXQQgKkCn8CkG2SB8T0ViGrPMF2+q3x2nTeHrI6eO5soQYp3sIk9K9N8EBpnuoigfz/t5yAboWIkPeurr6b0uELeNAvzKB0NAeKmIuJxsWzyvNkQ4LtuMohPJ8zrvtucU4HYNSUXGURcObnnUiCl0siVnbUds0=
    - secure: qGmXdn37nleSygbfv5ioR0mKJ9l289MNM2x1gmvWeXZRLaocL0JmOuHWwOMiT6peJu1ImF+hnWEl5ueyNPxG2jBLwxyRG9yLoHhqvXttRlwz8w12XDuhQ9LWBbiOge/SZrF6/IvUSAiw4FADZBiK3raH0Iu3vYBEzC2Ud9bfHcwuaqzt2ZpNa39XeJo1Ammw/xGcywB/KbEhMxNSROocSfqHyKINWJw6qvOs8Q+/0pWedvUkBTdqWJx5UxnF+v4iGMvDZ8FdNDyObDNjvIsrf8gKnc/e9I93Q86Frvkfo02CLXzV5s+CNwXBADCE/Bi7sFPaq/ExGwd+fZSkq7/6IoQanqW0y3CBnO5YSvbN8AG4+Mvj9Ty8vAlRYoljuQgMipINWmOo80nIogySp0kFJPcjqLPW0SxCrbH2nw7+vLm2Wvmz0aCC+WXdXqxBZcj/wIe+4P519jE5lXz3G4HPApi3DJl5vUnMqGqV4UmI+OL3tsppb1a8bsJhFi3cvzfYaM+iYMn4PyRpgXhbMdcDnzpHvULa+hse+rawXR9BeXi3N46FPEVNG1CBiqKRRFup3+OVuzEpYvB52Wf/XMxhYMgcqwjNd5tfuJ952Qkg67VFe09N9dW6NiG/ac5boczTjhHuHqkR5CDlS8LDNzqzp4YZhIabJvXL9q8gLfqbo24=
    - secure: VPFeeGOS5BVZ5pM6fkr7nVAj4+3kjtA2ivov7jFUw0rmBQaXCC8+y88idQPR2J4VtJWy9y70uVyVrc9YUxzVB4kx4N0a6RJgeLp809sFladenLfNrfOC213k6ucpqmuFKIaWAFnUkwgPmqix8UV/DunW05e93LyK/E9XqkDyjk3fO6fnI3PKloMJyWH+79KinESwlxcab83K0cSzW1eElmr0iejNcw9gVTudvLWjHzK/y6ndBWjM7eUGJ+NTXsV+Jm492ATbi9ObhAiPTOOYBMDdZ013bvtsUh0U8qSaLq4I/80QG1q5E95F6CWf/wMyQdbWfYLwXC1HL7OIrFlD0pBEA3PPWpR+trpADV8fa695GAqi6Ky8kEdZGa8NT9+9M4Swxya/VnEhV6PupOen4BoryEI0Q9DtaPhZIuC8C5eLH6BRpY96s9kTLcJg0urH6b3+Sj368FVZGorL2vx+9y0GYEDKvcfkG6hIaZNGSArM/wGyT94dFq+NJNKZOqAGuHYzLd6c/kE0nHT9HR9irVYrmrvRHAawMeMn38QmfbX9jjt9fHARQR6SzUWBfVEmg2CpGIjcb8GS/7X3R7OsdwmBrQ+VvOuea7/LByGFQjufEKXMkFtdcai4C4NelV9Rjn0kWJmpB07ZJoFg2+Y7sJQvw/USG67f+vWtdvgYsH8=
    - secure: Y75Wkt90XA86u/UchXcWmVkE08FmCccK3oSquNcJG0/2xPkpmOXZnEQ5wG50cKw0kBqrrhm0a8WjBLyNuc2hPE1s7wtVct/CCbBot//ahZW9PrFIoUGuH2f6VvKmKtU8qjKm3vqju1dMMij0Usg2dWnmkfharqAsWMuZBpCusrpqNA8ZGQlRIkVh34A54ebH/ZMEKWDwFBSSPNL7VPhIkV+zzwVc7OY40iO8+Xxy8PfxqU2WDFVKkFBBxvycQiF9byhbEl3xGmwLZcme1b0ZgBS5Ev/3DNr+nddlHtTyJY1R8QFWJ7eLC7pXr4U0AW5xvTEWH+okB19WTmPzlbEIdGD5GEar5NWG3SaL1QNxSbWkit32lkOB1DdPaD1R4sy6H2k9fOBcUPa86bQO2etQvhjXnn8yQ56OSSVH20ccqFwTaKVurP0tARo8Elc48LI0oXxqetPn7hpdS1hgNK7knEJtXI9IvCbPC9+MOGprYLLZ4YKK648kiIFWM/pVLe9QyRaG2r4Om6QJdbgqwRIFDo3FP5RfBNKUn3ChGkaeXjKV2EWTYQ0DIlDc3lkCJYnazr71u6LDdq8J/MZYBq2zfOerVIv+67HJB6PpYomJhiNLTpi5aPxdwVmmuss5gzSm5Ju5B0Nq/pQzxOoIlB5yBetw80mefG3EB00UsGuAsiI=
    - secure: hSfirFJx/nZLMVavRuTJlrujECqTKuBFh0cC6adEmaFL7WhoHnS+cZv2KtGI5eYuQ470+pg5LUWCF1nwCUhqwIV+9rhOEB1cvD1fRSHa4rEM3S1lkBWalIwcRlGPUwxgssqKr0zJq6CuwK/XSzRdGtKyaUJHHBpVpIMGnIVtm9iFrh7MM8GY1ztnDPUbvLG6Z2rQ8qq+8IqcQlth/xcDxjEglTD1tJe99nB0VAi71M3UYel64Hs8RFnk2V0ARoK/MEpNkEXBYSJeeLGA05RqKNTPKTN3WeOLgyakHGl9OUnZJjIy21V/r1pojeHhoDwFtGuEpDTX/aaaX8codyv3mdEZgUK4D1kJtgQJxFJi3shjB9O7kp9dECHB3p4XklOmZcQXR9Zdqovdb2y6o0GLbOOEKbUKM4pXvk2XCNmtrOmMEMIkzz7ejxL43WdvZ2irW8fVQVgiZcTFQ5ti4Apq76h3wqNRVIcypXJi+dGV3Xf7V6qfOOaW6GvQn3OlZTmpjJ6JStv49zfF3lD5uJipxGAsLSP6+oMMKOUJlN/qwvdeVaU7LTA2L3zHqzmTOdkUg8XO6e2Bl/DuArLk9j6uYbZE/v9QKJTWxbSF+vYb33+x2hcgmtgcsKP6gnearwka1kEfw4/8xYtwWED4zkfvLIsDgsNoPfG4EiqH35FdsgA=
    - secure: V37fo5zt3oLuj/QSVyyFI9z+R1u+m/4o+rkz6JKEesJzKO8aq/Goi/uKwTQVsK+zJ7c6swe1uhTH9A6VqaJKowqfXUxyO0XhXZnAUUenjAxG5OaLqtkfluQhPBPcXPHlatLPW/Oqqlswv05TKgaozBc55hdhH0qpQWLaxS2Gt11MbrbF7HoQevB9UJfO9Mn/F38KlFp5BiRP+zRKogAPJdyGnpd6ndLpa9Qvs60JCZXY66sav/BbMniQAZ4guOGORaxueKlpdX1z2xnCmD4jGuQnLdikx9/RVl2kutGCNfx73tsSAdMRKXI5YT9L9R/CB9fUpGEfdIADTbeOMOaFH96tUkelTErtt28mznoA2Wjif97TD5XpMxPc5nE+Sx1BPDb2+O+1wcutior+3eZUnjdoxo8ccfcf7rRmRDqqqkblMrASYPSmAlrHAukuC5EUizF0WVUCQbRgt0JJnDFfFYUXHSnRPedYgdFJmvrb7+GkbtJtcCPJfkK6sbYCpJwQJibkUJJYIzvmyQUyjeeQ0Z+KWK85F/G7BonLi1wAic1rBPvDgbQJwcGKaoYexTI23IZSYKc2rrPW7TPiUMiIPV49TMQez6cIFrdLjDTWvFyGqlOFnRES4FFASZR4P9HWRKNJcqCTwKg+Q61HdIaQdXoC5zwXGA0stXH2xNX6A+4=
    - secure: jSimf2X4zkaNaEEjOtNJW29F3XI3Jl7d3/0N3oShc7vjErgItB/eZintEhfpvPPthuv1f7vYU4uKtxHepwBjVReL6rw0zEyaRvHDB/YrspaZN+UzlBKV06NkCiFcTJtgX8i0UCARn99JZCE/FSp/kEKIe66Fv3uC6JuZctKPpKj8IvtpPKNq5/UxbDb+2Es0oa9vWjos0zsZuKf1OxA0D56hYXzrm+Pu2NqZAJNXbmKtNvYVE1tmljTz4kpJ4VIgJqrsXIpVaL2ZloO5Nn/pbvkdaXkFqkVOgfMdpnzpKp5CYCySfjVEFUMTbREmLwUuhl4kqQD63/pKvUDg5LG7HmCnmuyCWjNF2U/Z1hUVLHiIiPGGLcgJS/xloWIIB9VZVuq0DP6wa+VABXpfNVmpMKpLQuJRKzKo4TcJaMWYeUG72KqiQLzXA9GzaBspn4UEuoTlGZpm5TLDpYiLeqDQQQplA95nkDOdYDL1NGs/DKMAgyx1PT6MQWPSGPIUmxXX9dTA5S8I1EfMQdy94RWRkgIF0gKwgAB+ig2JeHJKJ+NoguXlryCQsrLrbttkYi85ZfZWxZSg2l++ZMwheDmNvmWiilHg2Rnu2b6q2u4H+NB/1xSnIGJ0HTAN9K/UHieoSZtpuF2eghDl7FUXHgCF/Diok48AUrerz98crsr0PT8=
    - secure: QKvABc+mqwcQfROecTjsvDMKu+NenSJmY05l0oHBZRHyWkzLauWHK0YAqHd9PVaejeBDZD167LJHK7PdxrKrLxH02tklpQKOGzI1XcAyRJn7YawyTKeUP/znaXC37xdhtKq+2SBRJoZPVzgbPYpZAlOM50y8BVWQ4ETKVZPw472B7GvE/DCS5I9aLFJQ+hb0v8/oPt87iR3biIZgOiswGxbk8TrWpNSBim13OWx+h7/x89HMjqal2i1fbHMsZtBtoE8n1IF2h8Jt9O8yujYmxOsT7iUIN/NffQ98RkrtIGWbO5tPVWWtTsbyT96kV0gWyUIN4QFHNoHNPwQOvrMj/7Faxx4Mfa5tnRnf5px5ZmjDfuh5ROzX/npgI7TT94uDJtv8IeyqyAOmbzNSiZpn9E72/yJY2cD+nOIMfywkcucZXJxrTqUUQk6YH3w+jVMyWPmUys0sD54NPkedPiI18/Esqc0L1arco+Slert55X+aavjBzfNatAt7g0E5ogKc3rJOerPK3n7M0j2XjUlTv82xZ436bX4UjN06D7V6QSSJ1bNS19TTanLBa1NvUQa533p1I0OZTYeVh1DE0yDgYXuthZP7rf8Q6ZSSf0G8UJiu8c+3feDqHXPbqr9pzWep+cFlLtL/MqjlKHVRMXs4OuHPKPWTXmjfxmoMNLQ81kE=
    - secure: pomAHaSYxqUTx+Zuv9AVbdHP09FUikn+UNCsxvJNwISLm/9mvv4uthalD9h6A4aHHKZVvIAAf1pnIDiO096A6eIDCqc0cH4JUEDJiqJlBMMg7X4qWhRx7A2oLUtfY+YfyO6ZvGmByuRzV7NgE9PLnrdPQTpsTNSt0/XAkzfXbBcCvsiygl7cJNchqpJu1+ojZnvTy1mEFBkc3MraisoYNq+auNa+lD/KSsiGS/zJWCL53l6yXg2yb65hrH0ov0PDoRSSLl/dedfgyQVa5lCCFskjE3wCIWucrtTuKhIek6XUbIQpcABE5hGfVdAODfLxT+rWc05/UHHbnZ+h2fNDnHndF5wyOtdmct652n9LOFIs2oANMxZqJuNFrNm5iuFj4MPheg9M4FowJ5Am46alkJ1stsUlT+FVR9wkSN/wWIElC8+PhW4EsCCO2ZytRt2loQKUk+XL+GV+XNYNwi7wdykqKN+kLKVnrl7tXzrE9JXoPTdhStIwbZ/VCntlIEt8FTinZ+E+EntNdUnDlmPZd/eGcDhpy+fCRohuTEwEaXPMkIUxlfBF21Z+TPK0bEkvwT+x7UFr/hus9wePNMDcA05SjftrjTyJutAw6QJ1MokF5MiBPRiZpwIA3/qMYtsU6Sp6cwTJWvDWdMZuLqgq2MV6qMG4S/fxhAkKw7ycD9w=
    - secure: UpvDkP4MgNeqUdFrxz/NOJjchd+R+QW9d+sUr/TdC34ukzNhKzgHeFSRc+abMOKjb6XjDfFOR30l6lKDad14v8gBE/xcakugkCeKeUrROJOvGqFZ+HJI2zl3XGrCbT4ZowhwmEYQxBuzxTijBGPIyXehXK3j9F+KhsQ9u+PxcKwWd43FKSB8Cte8gWFS6NV2Es5rZvmiSsrDj15TAGWxfPlZ2UbI0JFQ1/Y+exH9CNidW+VTuvqdyPZIkLgmVRcm5ZUgcR71iT1zw5B2wOhMWzxK8EY1k0ed3gbPSdkMy5D2J5sWALAEII5f9/IaAzCjgW/HZR6AnZ71CEjlQdtBQZZUYSOTtfJOR4jUjsA5ce3+bR5wy5/gzcA6hLrY9tS6OdWmNfHl/mY+cjaDcPhkmpKpOVjmdytEq7Z6M+vzM50Th8Uyv9FP0WWzdWqSaYaXMO9+3/joa8UnnByzCgq/FCLuVUIPGxGqOSkb/7um9HZyd+GeNxYWq9CtWwMKY1JjsT+FHceSEJMl5LbCHf6FGnimAeShegba5P0PlGKeII2sMnT50wGYviykdi7Z2bO5jCeegrCCL6kwxQHfX1Y4c5iAFl9qEykUwyPPo5Y+Kw5Ye01bZ8FHiI8nA8NY77byjOubivncKG5CEr+dM9Slu68psP8e69KuJ6Xw8LSr3Lw=
    - secure: vuY4UsnnZhsvXN1hfuVvypUD1MazfmHNDD7sUhwOR5F02T4sR8aIe5HR5ZEAu+cbNdocydd9UYsYRE+VY5krM/z6g4+J2NBV9ZDxNKF/p3oK0R4C2vT6XfxTlEieqfzlE8Pit6f7q9n+/+xebKs4RDX9b+lXmB6NcCd4FjXZxtR00Jt70a3F0x0qHp4Qa8ikfsNcHoihFl3vnRBnd429N6Jj/3ftGN01Ofd91kvyqFvhbk3o1xqxIbkZCvkbj/CrXJ49mkKQVETkorXrYY/snrW+i7z7JpFmcxU+zwxxRDfULr02V5g82IJOQSMaXZYoIcNtFdn1G3zaRnWaOSBWCAMybwZzjl+3c0VDTtHPNrkdbsSRv2xPf+zMKMJ9PZ7w+UDC2L4r6sC1cbYDVg+6SrDO83bIeWeUJyK8BpSx0n2tvoQI7fxyz52wSFpshY+XQ/yT7EA4GGo7+XailtleqeQXyBe+deupW1tNVX0z/cyA3xTsrsZIALGOgSaZUHMdlXBg0pVRNdSdTyZB2NbHt3QbzmrrChIzQwk0BDjo8S/aoHuSCRVeC34quFdnuKZflDRrF0Z0AEO/CF9G81UJ7SRkz53J2aj18ssEFJ/2TNU3jtZAbdVoFtTiudd4uz00/ku6IcAq6sl3CkskEFkqLPZYlom0pOhfP3ef5pjKHK4=
    - secure: DBqpYIXv/bT66KhhqEuwQbIdxCmqli8jg7Sk3m0ZnYs3Z2DVHkRte/Y3wswZiqE+nujX8qHcMzvGk9NN8l30Mv6jAfMgewNWW/Xu2oJ6ZAZm+cZRMskhMP/5TzVs3RmOz21rbODpHwA6DLVoebfg13JaFNMg8I+FoeBV8TqlAoElLztW9wkx7jZkmeXEJK1DWocGVtI08GSbCo6CqZDRIgf1SxqOQuHyCCAJ9EFVn6lxuUtnZNMWMPvbAsyh3WKsP97XxC3uzZq+7BUkynM9XlZ3mHYkYZWvoz/qn2sYXYV9y3Wn6+BHGvDW7R4coSp3dpSkvBna0aPO9wpBVkHss6lDYeRz65z6XOr2X2inLonoBmcg21ChIo45v1vs0OHP5jS2KroS+X2UVxhRbY4HuyN/0k3UmAnEO5h3864yXX00I/8oCbvARNl2pFjWObcBcGEUfue79t0jBz7hVlPHdfrSrRdDxKbxzeLxR9s1sKxqR2xLt/xEl72KTaK41liwAicc/2gvt3dGXQhrXEHRg0fGjU2HN6fywKOA2InnCAXRIA9ql5+0VsYiqZyy32AZaaXoXxF4zLAJlfh++wv+s05uzrwOAvonZqKIVS1eJNyLr51Xc0nV2lG5VCrm900raPw4h8toaA0zLuBNEiuOld+eFHowIRrD4o12JJ29eCs=
    - secure: mL9ZdIOnl0g5II4rQhwKTeSvKEPonzaj2FUGKbSOEwx0Ol89PdkvbZccKgucnIzeDyijx0Qf/icCdtCQd1bm0m5AJGV+JPUfqKbOUV6kh/DIOSrI6xlnewyjVbwPfe00bgaiOcTvnP80aoy44JEQu6SyAiXqm8n+pllIyRksPjxAHq+Ozsf35OZBFXm5ZufYjGa4E4JPgxA/cGY+WBWWaYy6TfoB7vLASzWinYwJBj2KjmNjqSnz23RF3HqG4hUQWz5W0D0SONrtedTkmYZ5r/NKlDmD4Tzs/pVd1giM8Z4mU0lbIV+5hZEBXNyBmiFSCHB3C7utomflsmmG/KDUC3Okh8Xyh4F7L64QYs8IV4bjMKkE6YeiZOjnQHWwIFkRDOrIvgw/7mlj4Q4UFIi3c4LPrzrGcA+Q2BDTfk0KDi/p75+Nq4PQeZlN+wwj7/ViTTKCEnBtudlafqQHWA6RgUmyFwFsA5Gh8QKinB0o/M9RStAjPerjxmVfMtZt54o92OMFaPAS4xbvh2u2TWLDZsuBSsKBzU8pDkBMeQl3IypSIYCZxv1I/6g6yHSGbN+3SUNwWPnq8iv9U7aYqDw5/Ni9LhC79/xXr9s4LZTo51BrWT+rPOHzhev7s9rNJbM+6WgTscblHjK+OJxUkP0SzdklZEhLBF/5X6ATz8UoYlk=
    - secure: Hkgc3LS2+ihYneHyG9ib7scO9eTvH3VhxHmlU1FI6rFjkbz6oLvM1SaJdnpo/4enIiPLSjVzd5p50zuEP46tJBBMRboJZb4/vTfb0QFA5VwtAiQoHyiyDO7x/6j5uGB7EJc102u/IUjC5EeM5MlsQYoE47E37K5ojNUNOQin7PLAWiDxwJ6C8DWzhhTT3D4T7v0zpdxyOQTDHhqE/CwwqaCGvBZxGxrjwtAIHXGekX2yknXgy4OHHvZBnInyHT+QP1oOXLsHp8ZtLaT4UZk96VSsjGM6CzavUm3OG8qx+sU/5Vin5Y/1pN/yVgzHayctKIw5q632FeyD/jtaLgsibUbszr0y7K+of/9LMzAYZEHdEmBXYjxdoqVDChxKgiLg1nCoQ2tETTJpmfrsSSgFmeCfBEFmZCpascigYnFqfbyBu9vwppvihdogm66VMqwU2FXPmOczNopYZYpO6yJcuMEbiEJdYYimpIByZukXdQX8q/h1kx6dcBK+kSnFoBWFcQbaPblOIVqHuO5O76b0Xl1AtS/VYIUfa6dlbzKNnyR+krxf4WFUep/X8vZpbegP4nE+VDX1aPMDTWy3ew6uP+lThFBJsmQGabX1PU9s1iVwb2Z+lgukPtdPfj2RLpLq/IzwuG64a4XstxRKnbhtHlfdvmrbRXCoq2uCerd+BBc=
    - secure: vR9kk75nDGKTbBCaPLwH3bSkkUnu9o/Mr1rU7gBTyG9L3s6SzHQkUvxLVpjEuEgzx4mpqBaJIzbNA7txCnZkvQ5vfozcuPmrfXTaifw5MpIAi2a1uSN2ctZh32bhR5m+OfPGvmKyXMRvgQSlG3cO+lekWRvfNAwhU+vMwi9E2HBXVXBifJMWTg3aFU6wISGRea7OhFdfb5ROpFVqR3chAAevnd4UeOjY7VczZx/w8MeyhzYqNgiZJ5q132vpapAsKEBQBM6HJAdRgmlLYEZHtjh9ROD+dnZSmUAEj/NdHqglBMif0yW4W5X+SKWLF1xEUkYXT0/tPzYXHwcHsStnKUJhKmdlOuNYSzX+q75QNbi+yxNnqWcSeMNtN5E7n/MYsRDQVY1uo35q1C2iTOWHrWaGE8RJrSXPxdh7Lq0wFVSm8ofUW9+vBCFZ0vxspngJqIaJpZyPbOxKvWADd+r14j6cQFo+FL+QNUO1uQLz4XPrJW6sU6uT2MTBDDTQdH4tWtswpAuc475d389FRsnyiKd/c886rRULIUq6oRI5fMlFe+8WLw3QAzs22toH2xgXChSkHnBF71/FAW+79v+lOmy8J5kE7ZJcROq8meBWH4ASk089FRWv3wjjOVvTXx0O6XU+7jmS5fLPEtpoanuNdFfPGzN6e1JLbwElP2UwpY8=
    - secure: ea6+BvenROTG7giVAJiMVsGPX2QLbl+NVEN09cxq6gZJIqsdr+UN6S8RGMTNAZibmeagj5gMF4fQ2tOwgCl5mUfFStk3dXeZYJ6bu358KLrDvqTELoQr6pMgsWc04L0dd/7xUBH0krMc4XCkOT8aNdNif+UCjPoIBEKuKBSviVoEfxVwh7cTb5GJ1UmozqTZlxf0/2lBVNC8EYylHWyhQ7Si94CNQbOlvqq97EOjA7qN7y3m6IpLvkOZ0JUqc5gQcdETtocIbgc6crrSv5c1cUAmryL61gA25qPyedydK2uRsgNgO+JfZdN3+JoKWhyKhfNzvnMITk0tneEYYgLSauEt1b/+loYbd5yNIhvKcynKsUTkzafyVV1dMmz/Bm9qS6DGjdixHK/UTzXThjyUVmzMpuAPrRdEHq1r/1R7rmgPrPR2TWCu3zDhvWSbh4jfJ7tQaue9+7pzJ0VOYxfnwLX1c2cP6CkZFgy9tUsmrLARS54f2BK8dWW2uqJFQre4+IlKKznn5eIuyxzH0dbkNU1gM9UX7RYV3IM5fM54H2ANoF2z9PsHmJw0f9bSp+Z4rAGZ8PVInx3gH6t7dp2cU3suK2+sJUhzkBDXzd/DqCdbM75IFTyPGrMOVb+MXQ+MqBwzp7NCb40nO6Ob+0VmmvmhzdZu/sjjyZ2rC+5c+qg=
  matrix:
    secure: aqcGPDGxdYhbW6Cq6JFKHmyjYBqkDgDlONgM43o5ES1yIiqdFG0LySL75XE2QBocyyG/a1tNMj6aX4nrLrsukmNlEgXieWjuQs3EaTjVHiw+JWhU6yDcI4PqF4ZoD3ANdghxkBWQ8YjL+tfHfwCSnewI0UnRBsrb76Yv81o/Frkr+1zAkw4kG/6ubS5eRGcA9xOOvo0VDkz8HtsWnbxfAfLMBhsPICmdj7KlZJZY2hjfD+okf3DcKQqZZPi7bqfDb7AGmTKufX2QUVFRbT1p6yp+xH5hOB5QK2/2YeSXNntkzO2NhXsiyVybBTAhnulTsQMbCv6RELmXIm0/BHS0bhPzrK8NbQJPrYHPVYV93Z3S4Lpg1rzPAPIDf124V7CAcTYZEXgjS6YRUMMPwA0GJJDbNuJnwGiVGL4J95dkllf9h2BSym0zsPhtU94OPQvWs3VyfaK3uz6z9X/CmeeCuhOcPYV9NWX5J+6swI/tttYdnNdOa5j5PCoVtRD6hIB0YsBpxLSOIOjugXyQXNn+rWQbvoTZjQMPInAk/Bhav5IGXC+Xa2MesXJh6Nu7WXdwXxXEwVNJ4/jJULNsP7NTer0G43akzkI4m4Fairw3mo8HXdhQ+nmMyUU9xqmPWvgSNsI9JiBxTMu8xmN36cdmNiBqW+GWa0iBzlXTq2zK9lQ=


matrix:
  include:
    - os: linux
      env: PLATFORM='Unit Tests'
      language: node_js
      node_js: ${UNIT_TESTS_NODEJS_VERSION}
      script: 
        - npm run test


    - os: linux
      if: type IN (pull_request)
      env: PLATFORM='HTML5'
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      sudo: enabled
      script: 
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform html5


    - os: linux
      if: type IN (pull_request)
      env: PLATFORM='NativeScript Android'
      language: android
      jdk: oraclejdk8
      before_install: nvm install ${INTEGRATION_TESTS_NODEJS_VERSION}
      install:
        - echo no | npm i -g nativescript@${INTEGRATION_TESTS_NATIVESCRIPT_VERSION}
        - npm i
      before_script:
        - echo no | android create avd --force -n test -t android-24 -b armeabi-v7a
        - emulator -avd test -no-window &
        - android-wait-for-emulator
      script:
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform nativescript --os android


    - os: osx
      if: type IN (pull_request)
      env: PLATFORM='NativeScript iOS'
      osx_image: xcode9.2
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      jdk: oraclejdk8
      before_install:
        - deviceId=$(xcrun simctl create 'iPhone7-11.2' com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus com.apple.CoreSimulator.SimRuntime.iOS-11-2)
        - xcrun simctl boot $deviceId
      install:
        - echo no | npm i -g nativescript@${INTEGRATION_TESTS_NATIVESCRIPT_VERSION}
        - tns usage-reporting disable
        - tns error-reporting disable
        - npm i
      script:
        - echo no | tns device ios
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform nativescript --os ios


    - os: linux
      if: type IN (pull_request)
      env: PLATFORM='PhoneGap Android'
      dist: precise
      language: android
      jdk: oraclejdk8
      before_install: nvm install ${INTEGRATION_TESTS_NODEJS_VERSION}
      install:
        - echo no | npm i -g cordova@${INTEGRATION_TESTS_CORDOVA_VERSION}
        - npm i
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-window &
        - android-wait-for-emulator
      script:
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform phonegap --os android


    - os: osx
      if: type IN (pull_request)
      env: PLATFORM='PhoneGap iOS'
      osx_image: xcode9.2
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      jdk: oraclejdk8
      install:
        - npm i -g cordova@${INTEGRATION_TESTS_CORDOVA_VERSION}
        - npm i
      script:
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform phonegap --os ios


    - stage: deploy
      script: skip
      language: node_js
      node_js: ${UNIT_TESTS_NODEJS_VERSION}
      if: tag =~ ^v?([0-9])*\.[0-9]*\.[0-9]*(-\w+)?$
      deploy:
        provider: script
        script: ./node_modules/.bin/lerna run release --parallel
        skip_cleanup: true
        on:
          branch: master
          tags: true  
   

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-24


notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    secure: zhQEKSmoMrI5yj180Z8NtAqujmMgRI3TIO/DrnFEDjuXziBanKr2Thnzup0Gmr5vfOA1c3yh/HVs671188UDsE6YSf/r8ephjE+dzlk3iyYE6ViHUHB7ju+DKyGOeNPk8yMFUqDhLhtQ9wA8Bvlzbfn/ZwPk2ArDZgp3ixBEmIzB/gkcq4EC+2ciJbBUh99fOPUYspvAvf4xLlQRPNiuZ/BSCfeASRkvYdUp9kAMZecIt2EfAneTAOyEBKc+8ob24Yu5L8GfSnNa8qeAmzwki6WGaVR7EantJ0SA/dXyISlj08ckW/MEY5hoBhy1x0/gsaPaLNfq/GRz1Zj69Qmqz359tknuRBC4lMmEyutG9SKNBB8OAtNyUUnnNi45P+fyTUP/4l+4tYEN4hj/ncnFKvW5P5ls/LZ84wpjfAiUlkVqSwKXUnzccYDYNBfeVMEpTwoxctBgRp9Akalf3nVYfZHvH+/Sy3VGzDqagF+55+kTgfPmf763lKbOanr2HNzpvIfT21UyZ2EEDAoAkqr65HbA+yYgs/Awni02qzalafmIbP3aF9a3yULftubAvfsKALjrde38iqE5kOvsyiFOjescA7chdpJqudn6sT6SuYHaVoaBzqKX0t2aLWq8a9rMoS1qKW22IQ2CQilAtVG5Nb19mcUSjkisoIYnrCvK700=
