name: 'nativescript -> npm'

on:
  workflow_dispatch:
    inputs:
      bump_version:
        description: 'Bump Version'
        required: true
        default: true
        type: boolean
      next_version:
        description: 'Next Version with Next tag'
        required: true
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  release:
    runs-on: macos-latest

    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22.14.0

      - name: Setup
        run: npm i --ignore-scripts --legacy-peer-deps --no-package-lock

      - name: Bump Standard Version
        if: github.event.inputs.bump_version == 'true'
        run: |
          npm run release

      - name: Generate Version
        run: |
          echo NPM_VERSION=$(node -e "console.log(require('./package.json').version);") >> $GITHUB_ENV

      - name: Bump Version
        if: github.event.inputs.next_version == 'true'
        run: npm version $NPM_VERSION

      - name: Build nativescript
        run: npm pack
      
      - name: npm ENV
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      - name: Publish next nativescript version
        if: github.event.inputs.next_version == 'true'
        run: |
          echo "Publishing nativescript@$NPM_VERSION to NPM with tag $NPM_TAG..."
          npm publish akylas-nativescript-cli-$NPM_VERSION.tgz --tag $NPM_TAG

      - name: Publish nativescript
        if: github.event.inputs.next_version == 'false'
        run: |
          echo "Publishing nativescript@$NPM_VERSION to NPM..."
          npm publish akylas-nativescript-cli-$NPM_VERSION.tgz 

      - name: Push to git
        if: github.event.inputs.bump_version == 'true'
        run: |
          git push origin --tags
          git push origin
